name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## Thanks for filing this out ❤️!"
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction steps"
      placeholder: How can we reproduce the issue?
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      placeholder: Provide any additional information.
    validations:
      required: false
