name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "💡 [REQUEST] - <title>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## Thanks for filing this out ❤️!"
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      placeholder: Provide a brief explanation of the feature...
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      placeholder: Provide a basic example of how the feature would work...
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      placeholder: Provide any additional information.
    validations:
      required: false
