[package]
name = "use"
type = "bin"
authors = ["Distributed Lab"]
license = "MIT"
description = "PLUME usage in Noir."
compiler_version = ">=0.35.0"

[dependencies]
plume = { path = "../plume" }
bignum = {tag = "v0.3.7", git = "https://github.com/noir-lang/noir-bignum"}
noir_bigcurve = {tag = "v0.4", git = "https://github.com/noir-lang/noir_bigcurve"}