[package]
name = "use"
type = "bin"
authors = ["Distributed Lab"]
license = "MIT"
description = "PLUME usage in Noir."
compiler_version = ">=0.35.0"

[dependencies]
plume = { path = "../plume" }
# ec_ops_test = { path = "../ec_ops_test" }
