[package]
name = "plume"
type = "lib"
authors = ["Distributed Lab"]
license = "MIT"
description = "PLUME implementation in Noir."
compiler_version = ">=0.35.0"

[dependencies]
bignum = {tag = "v0.3.6", git = "https://github.com/noir-lang/noir-bignum"}
