[package]
name = "plume"
type = "lib"
authors = ["Distributed Lab"]
license = "MIT"
description = "PLUME implementation in Noir."
compiler_version = ">=0.36.0"

[dependencies]
bignum = { tag = "v0.4.2", git = "https://github.com/noir-lang/noir-bignum" }
noir_bigcurve = { path = "../../../honkdrop/lib/noir_bigcurve" }
