name: Noir CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly, 0.36.0]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3   
        with:
          toolchain: ${{ matrix.toolchain }}
      
      - name: Run nargo check
        run: nargo check --silence-warnings  
      
      - name: Run nargo test
        run: nargo test --silence-warnings  
  
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: 0.36.0

      - name: Run formatter
        run: nargo fmt --check      
