name: Noir CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3   
        with:
          toolchain: 0.36.0 

      - name: Run nargo fmt
        run: nargo fmt --check
      
      - name: Run nargo check
        run: nargo check --silence-warnings  
      
      - name: Run nargo test
        run: nargo test --silence-warnings  
