name: Noir CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Nargo Binary
        uses: actions/cache@v4
        id: nargo-cache
        with:
          path: ~/.nargo/bin/nargo
          key: ${{ runner.os }}-nargo-binary
          restore-keys: |
            ${{ runner.os }}-nargo-binary

      - name: Create `.nargo/bin` directory
        shell: bash
        run: |
          mkdir -p $HOME/.nargo/bin
          echo "${HOME}/.nargo/bin" >> $GITHUB_PATH

      - name: Install Noir
        if: steps.nargo-cache.outputs.cache-hit != 'true'
        run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/noirup | bash -s -- \
                  -C 51ae1b324cd73fdb4fe3695b5d483a44b4aff4a9    

      - name: Run nargo fmt
        run: nargo fmt --check
      
      - name: Run nargo check
        run: nargo check --silence-warnings  
      
      - name: Run nargo test
        run: nargo test --silence-warnings  
